#!/bin/bash
echo -e "To install power the Stunnel Multi Certificate"
echo -e "You need to have the Stunnel Normal installed"
echo -e "Continue?"
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[Y/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
echo -e "Enter a name for your new certificate SSL"
echo -e "Exemple: SSLMexico"
read -p ": " certssl
echo -e "Write the Service port to SSH or Dropbear"
echo -e "Ejemplo: 22"
read -p ": " portserv
echo -e "Enter the New SSL Port to use"
read -p ": " portssl
if lsof -Pi :$portssl -sTCP:LISTEN -t >/dev/null ; then
echo "That port is already in use" 
extra
else
openssl genrsa 2048 > $certssl.key
openssl req -new -key $certssl.key -x509 -days 1000 -out $certssl.crt
cat $certssl.crt $certssl.key > $certssl.pem
mv $certssl.pem /etc/stunnel/
echo "[$certssl] " >> /etc/stunnel/stunnel.conf
echo "cert = /etc/stunnel/$certssl.pem " >> /etc/stunnel/stunnel.conf
echo "accept = $portssl " >> /etc/stunnel/stunnel.conf
echo "connect = 127.0.0.1:$portserv" >> /etc/stunnel/stunnel.conf
sleep 5
echo "Reiniciando Servicio : Stunnel4"
service stunnel4 restart 1> /dev/null 2> /dev/null
sleep 5
fi
fi
echo -e "\033[1;31mPRESS ENTER FOR CONTINUE\033[0m" | lolcat -a
read -p " "
extra