#!/bin/bash
vpspackversion=5.1
OS=`uname -m`;
host=`hostname`;
ip=`cat /etc/VpsPackdir/ip`;
function stunnelnm(){
echo "Installing Stunnel, Wait..."
bash /etc/VpsPackdir/ssl
}
function stunnelmulti(){
echo "Installing Stunnel, Wait..."
bash /etc/VpsPackdir/sslmulti
}
if [[ $1 == "" ]]
then
clear
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m ───────────────── /// ──────────────────\033[1;33m" | lolcat -a
echo -e "\033[0;34m================================================\033[0m"
echo -e "\033[1;33m           WELCOME TO JOKER TEAM                \033[0m"
echo -e "\033[0;34m================================================\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m ───────────────── /// ──────────────────\033[1;33m" | lolcat -a
echo -e "\033[1;37m › IP Publica VPS:\033[1;32m$ip \033[0m" | lolcat -a
echo -e "\033[1;37m › Hostname VPS:\033[1;32m$host \033[0m" | lolcat -a
echo -e "\033[1;37m › M: $memoriatotal MB ›Uso: $memoriauso MB ›Libre: $memorialibre MB\033[0m" | lolcat -a
echo -e "\033[1;37m › P:$processor\033[0m" | lolcat -a
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m ───────────────────────────────────────\033[1;33m" | lolcat -a
echo -e "\033[1;37m     STUNNEL SSL\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m ────────────────── /// ────────────────\033[1;33m" | lolcat -a
echo -e "[\033[1;32m1\033[1;33m]   \033[1;31m› \033[1;33mSTUNNEL NORMAL\033[1;33m
[\033[1;32m2\033[1;33m]   \033[1;31m› \033[1;33mSTUNNEL MULTI CERTIFICADO\033[1;33m
[\033[1;30m0\033[1;33m] < REGRESAR \033[1;33m
[\033[1;31m-\033[1;33m]\033[1;31m ───────────────── /// ─────────────────\033[1;33m" | lolcat -a
echo -e "\033[1;33m      ⋤⋥ WRITE IN OPTION:      \033[0m" | lolcat -a
read -p " : " opcao
tput cuu1 >&2 && tput dl1 >&2
else
opcao=$1
fi
case $opcao in
1 | 01 )
stunnelnm;;
2 | 02 )
stunnelmulti;;
0)
extra;;
esac